import React from 'react'
import Editor from './components/Editor'
import Sidebar from './components/Sidebar'
import {data} from './data'
import Split from 'react-split'
import {nanoid} from 'nanoid'
